# This file was autogenerated by the 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# Avoid mixing go templating calls ( for example ```{{ upper(`string`) }}``` )
# and HCL2 calls (for example '${ var.string_value_example }' ). They won't be
# executed together and the outcome will be unknown.

# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/source
source "lxc" "lxc-centos-7-x64" {
  config_file         = "/etc/lxc/default.conf"
  template_name       = "download"
  template_parameters = ["-r", "3.17", "-a", "amd64", "-d", "alpine"]
}

source "lxc" "lxc-jessie" {
  config_file               = "/etc/lxc/default.conf"
  template_environment_vars = ["SUITE=jessie"]
  template_name             = "debian"
}
#
#source "lxc" "lxc-trusty" {
#  config_file               = "/etc/lxc/default.conf"
#  template_environment_vars = ["SUITE=trusty"]
#  template_name             = "ubuntu"
#}
#
#source "lxc" "lxc-xenial" {
#  config_file               = "/etc/lxc/default.conf"
#  template_environment_vars = ["SUITE=xenial"]
#  template_name             = "ubuntu"
#}

# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/build
build {
  sources = ["source.lxc.lxc-centos-7-x64", "source.lxc.lxc-jessie"]

}
