distribution      = "debian"
dns_search_domain = "compnor.local"
dns_1             = "192.168.1.6"
dns_2             = "192.168.1.9"
arch              = "amd64"
application       = "pihole"
version           = "0.0.1"
base_image        = "debian:latest"