# This file was autogenerated by the 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# Avoid mixing go templating calls ( for example ```{{ upper(`string`) }}``` )
# and HCL2 calls (for example '${ var.string_value_example }' ). They won't be
# executed together and the outcome will be unknown.

# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/source
packer {
  required_plugins {
    lxc = {
      version = ">= 1.0.0"
      source  = "github.com/hashicorp/lxc"
    }
  }
}

#source "lxc" "lxc-trusty" {
#  config_file               = "/home/jpancoast/image-builder/lxc/tutorial/ubuntu.lxc.conf"
#  template_environment_vars = ["SUITE=trusty"]
#  template_name             = "lxc-download"
#}
#
#source "lxc" "lxc-xenial" {
#  config_file               = "/home/jpancoast/image-builder/lxc/tutorial/ubuntu.lxc.conf"
#  template_environment_vars = ["SUITE=xenial"]
#  template_name             = "ubuntu"
#}

source "lxc" "ubuntu-xenial-amd64" {
  config_file = "/etc/lxc/default.conf"
  template_name = "download"
  output_directory = "/home/jpancoast/image_builder_output/ubuntu-xenial-amd64"
  container_name = "ubuntu-xenial-amd64"
  
  template_parameters = [
          "-d", "ubuntu",
          "-r", "xenial",
          "-a", "amd64"
  ]
}

#
#      "type": "lxc",
#      "config_file": "/etc/lxc/default.conf",
#      "template_name": "download",
#      "template_parameters": [
#          "-d", "ubuntu",
#          "-r","18.04",
#          "-a", "amd64"
#
# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/build
build {
#  sources = ["source.lxc.lxc-trusty", "source.lxc.lxc-xenial"]
  sources = ["source.lxc.ubuntu-xenial-amd64"]
}
